<a href="https://colab.research.google.com/github/sebasDev2001/ProyectoFinal/blob/main/Pytorch_and_tf_keras_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Learning Pythorch and more tk/keras ml**



# Set-up

In [ ]:
from sklearn.datasets import load_files       
import numpy as np
import matplotlib.pyplot as plt
import random
import cv2
import seaborn as sns

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dropout, Flatten, Conv2D,MaxPooling2D, Dense, Activation, SeparableConv2D, AveragePooling2D
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.callbacks import ModelCheckpoint, Callback, EarlyStopping
from keras.utils import np_utils
import os
from glob import glob # para recojer los datos mas facil
from tqdm import trange

from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from sklearn.model_selection import train_test_split
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.optimizers import SGD
from os import makedirs
from os import listdir
from shutil import copyfile
from random import seed
from random import random
import random
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0

def read_image(file_path, ROWS = 64,COLS = 64):
  img = cv2.imread(file_path, cv2.IMREAD_COLOR)
  return cv2.resize(img, (ROWS, COLS))

def prep_data(images, ROWS = 64,COLS = 64,CHANNELS=3):
  count = len(images)
  data = np.ndarray((count, ROWS, COLS, CHANNELS))
  for i, image_file in enumerate(images):
    image = read_image(image_file,ROWS,COLS)
    data[i] = image   
  return data

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')


Mounted at /content/drive/


In [ ]:
!ls "/content/drive/My Drive/"

In [ ]:
!unzip "/content/drive/MyDrive/archive.zip"

In [ ]:
#getting images
classes = ['cane', 'cavallo', 'elefante', 'farfalla', 'gallina', 'gatto', 'mucca', 'pecora', 'ragno', 'scoiattolo']

dir = '/content/raw-img'
imagesPre = []
for tipo in classes:
  aux = classes.index(tipo)
  path = os.path.join(dir, tipo)
  for img in os.listdir(path):
    try:
      dir2 = os.path.join(path, img)
      #img = cv2.imread(dir)
      imagesPre.append([dir2, aux])
      #imagesLabels.append(aux)
    except Exception as e:
      pass

random.shuffle(imagesPre)
'''for i in images[:10]:
    print(classes[i[1]])'''
images = []
imagesLabels = []

for i in imagesPre:
  images.append(i[0])
  imagesLabels.append(i[1])



In [ ]:
imagesLabels = np.array(imagesLabels)
images = np.array(images)
imagesLabels

In [ ]:
np.unique(imagesLabels,return_counts=True)

In [ ]:
images

In [ ]:
#image to data
ROWS = 64
COLS = 64
CHANNELS = 3
images = prep_data(images,ROWS=ROWS,COLS=COLS)
images = images/255.0




In [ ]:
data = images.astype(np.float64)
data = 255 * data
images = data.astype(np.uint8)


In [ ]:
images.shape

(26179, 64, 64, 3)

In [ ]:
plt.figure(figsize=(15,20))
for i in range(100):
    plt.subplot(10,10,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(images[i])
    plt.xlabel(classes[imagesLabels[i]])
    #plt.xlabel(classes[imagesLabels[i]])
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_val, Y_train, Y_val = train_test_split(images,imagesLabels, test_size=0.2, random_state=7, stratify=imagesLabels) #stratify es equitativo

In [ ]:
test = X_train.copy()
type(test[0][0][0][0])

numpy.uint8

In [ ]:
test = (test/255).astype(np.uint8)

In [ ]:
test[0]

#Torch

In [ ]:
import torch
import torch.nn as nn

class learnNet(nn.Module):
  def __init__(self):
    super(learnNet,self).__init__()
    '''self.conv1 = nn.Conv2D(3, 6, 4)
    self.act1 = nn.ReLu()
    self.conv2 = nn.Conv2D(6, 10, 4)
    self.conv3 = nn.Conv2D(10, 16, 4) #58
    self.pool = nn.MaxPooling2D(2,2) #29'''
    self.l1 = nn.Linear(64*64,2048)
    self.l2 = nn.Linear(2048,512)
    self.l3 = nn.Linear(512, 100)
    self.l4 = nn.Linear(100, 10)
    self.act = nn.ReLU()


  def forward(self, x):
    #print(x.shape)
    x = self.l1(x)
    #print(x.shape)
    x = self.act(x)
    x = self.l2(x)
    #print(x.shape)
    x = self.act(x)
    x = self.l3(x)
    #print(x.shape)
    x = self.act(x)
    x = self.l4(x)
    #print(x.shape)
    return x 





In [ ]:
X_train.reshape((-1,64,64))

X_train[0]

array([[[0.87058824, 0.81176471, 0.7372549 ],
        [0.85882353, 0.80392157, 0.7254902 ],
        [0.86666667, 0.80784314, 0.72941176],
        ...,
        [0.8627451 , 0.78431373, 0.71372549],
        [0.85882353, 0.78039216, 0.71372549],
        [0.8627451 , 0.78431373, 0.71764706]],

       [[0.87843137, 0.81568627, 0.74901961],
        [0.86666667, 0.80392157, 0.7372549 ],
        [0.87843137, 0.81568627, 0.74901961],
        ...,
        [0.85098039, 0.78039216, 0.73333333],
        [0.85098039, 0.78039216, 0.73333333],
        [0.84313725, 0.77647059, 0.7254902 ]],

       [[0.88235294, 0.81568627, 0.75686275],
        [0.87058824, 0.80784314, 0.74509804],
        [0.90196078, 0.83921569, 0.77647059],
        ...,
        [0.83137255, 0.76470588, 0.7372549 ],
        [0.84705882, 0.77647059, 0.74901961],
        [0.84705882, 0.78039216, 0.75294118]],

       ...,

       [[0.38039216, 0.69411765, 0.82352941],
        [0.49411765, 0.78823529, 0.92156863],
        [0.48627451, 0

In [ ]:
model = learnNet()
X = torch.tensor(X_train[2].reshape((-1,64*64))).float()
Y = torch.tensor(Y_train[2]).long()
out = model(X)
cat = torch.argmax(out, dim=1)
acc = (cat == Y ).float().mean()
acc

tensor(0.)

In [ ]:
model = learnNet()
BS = 30
optim = torch.optim.Adam(model.parameters())
loss_func = nn.CrossEntropyLoss()
losses , accuracies = [], []
for i in range(100): #10 epocas
  selection = np.random.randint(0,X_train.shape[0], size=(BS))
  X = torch.tensor(X_train[selection].reshape((-1,64*64))).float()
  Y = torch.tensor(Y_train[selection]).long()
  print(Y,"hi")
  optim.zero_grad()
  out = model(X)
  cat = torch.argmax(out, dim=1)
  acc = (cat == Y ).float().mean()
  loss = loss_func(out, Y)
  loss.backward()
  optim.step()
  loss, accuracy = loss.item(), acc.item()
  losses.append(loss)
  accuracies.append(accuracy) 
  print('loss %.2f accuracy %.2f' % (loss, accuracy))

plt.ylim(0,2)
plt.plot(losses)
plt.plot(accuracies)


tensor([4, 8, 5, 6, 2, 8, 5, 3, 0, 4, 3, 4, 7, 3, 7, 8, 4, 8, 5, 0, 4, 0, 3, 6,
        8, 5, 0, 8, 0, 3]) hi


RuntimeError: ignored

#Tensorflow MNEST


In [ ]:
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='')
tf.config.experimental_connect_to_cluster(resolver)
# This is the TPU initialization code that has to be at the beginning.
tf.tpu.experimental.initialize_tpu_system(resolver)
print("All devices: ", tf.config.list_logical_devices('TPU'))
strategy = tf.distribute.TPUStrategy(resolver) #estrategia para distrbibuir en los tensor cores

## Model 1 && Model 2

In [ ]:
with strategy.scope():
  model = Sequential()

  model.add(SeparableConv2D(64, (3, 3), input_shape = (32, 32, 3), activation = 'relu', padding='same'))
  
  model.add(Conv2D(64, (3, 3), activation = 'relu',padding='same'))
  model.add(MaxPooling2D(pool_size = (2, 2)))
  model.add(Conv2D(128, (3, 3), activation = 'relu',padding='same'))
  model.add(MaxPooling2D(pool_size = (2, 2)))
  model.add(Conv2D(128, (3, 3), activation = 'relu'))
  model.add(Conv2D(128, (3, 3), activation = 'relu'))
  #model.add(MaxPooling2D(pool_size = (2, 2)))

  model.add(Flatten())
  model.add(Dense(units = 64, activation = 'relu'))
  model.add(Dropout(0.2))
  model.add(Dense(units = 10, activation = 'softmax'))

  model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy','mse'])

In [ ]:
model.summary()

In [ ]:
with strategy.scope():
  model=Sequential()
  model.add(Conv2D(32,kernel_size=(3,3),input_shape=(64,64,3), padding='same'))
  model.add(Conv2D(32,kernel_size=(3,3)))
  model.add(MaxPooling2D(pool_size=(2,2)))
  model.add(Conv2D(32,kernel_size=(2,2)))
  model.add(MaxPooling2D(pool_size=(2,2)))
  model.add(Flatten())
  model.add(Dense(128, activation=tf.nn.relu))
  model.add(Dropout(0.2))
  model.add(Dense(10, activation=tf.nn.softmax))
  model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy','mse'])

In [ ]:
model.summary()

## Using MobileNetV3 

In [ ]:
im_size = (32,32,3)


9420800/9406464 [==============================] - 0s 0us/step


In [ ]:
with strategy.scope():
  basenet = tf.keras.applications.MobileNetV2(input_shape=im_size,include_top=False, weights='imagenet')
  basenet.trainable = False
  NewModel = Sequential()
  NewModel.add(basenet)
  NewModel.add(Flatten())
  NewModel.add(Dense(128, activation=tf.nn.relu))
  #NewModel.add(Dropout(0.2))
  NewModel.add(Dense(10, activation=tf.nn.softmax))
  NewModel.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy', 'mse'])
  

In [ ]:
NewModel.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 mobilenetv2_1.00_224 (Funct  (None, 1, 1, 1280)       2257984   
 ional)                                                          
                                                                 
 flatten_9 (Flatten)         (None, 1280)              0         
                                                                 
 dense_18 (Dense)            (None, 128)               163968    
                                                                 
 dense_19 (Dense)            (None, 10)                1290      
                                                                 
Total params: 2,423,242
Trainable params: 165,258
Non-trainable params: 2,257,984
_________________________________________________________________


In [ ]:
NewModel.evaluate(test_X,test_y)

313/313 [==============================] - 16s 26ms/step - loss: 2.2993 - accuracy: 0.1030 - mse: 27.6101


[2.2993111610412598, 0.10300000011920929, 27.610126495361328]

In [ ]:
from keras.datasets import mnist, cifar10 
from tensorflow.keras.preprocessing import image
import tensorflow_datasets as tfds

In [ ]:
food101_imges, labels = image, label = tfds.as_numpy(tfds.load(
    'food101',
    split='test',
    batch_size=-1,
    as_supervised=True,
))

In [ ]:
(train_X, train_y), (test_X, test_y) = cifar10.load_data()

In [ ]:
train_X.shape


(50000, 32, 32, 3)

In [ ]:
train_X, test_X = train_X/255.0, test_X/255.0

In [ ]:
X_train, X_val, Y_train, Y_val = train_test_split(train_X,train_y, test_size=0.2, random_state=7, stratify=train_y)

In [ ]:
NewModel.fit(X_train,Y_train, epochs=10, validation_data=(X_val,Y_val))

Epoch 1/10
1250/1250 [==============================] - 37s 24ms/step - loss: 1.9370 - accuracy: 0.3015 - mse: 27.6175 - val_loss: 1.8816 - val_accuracy: 0.3130 - val_mse: 27.6198
Epoch 2/10
1250/1250 [==============================] - 29s 23ms/step - loss: 1.8303 - accuracy: 0.3344 - mse: 27.6207 - val_loss: 1.8480 - val_accuracy: 0.3273 - val_mse: 27.6213
Epoch 3/10
1250/1250 [==============================] - 29s 23ms/step - loss: 1.7908 - accuracy: 0.3488 - mse: 27.6218 - val_loss: 1.8364 - val_accuracy: 0.3330 - val_mse: 27.6221
Epoch 4/10
1250/1250 [==============================] - 29s 23ms/step - loss: 1.7628 - accuracy: 0.3588 - mse: 27.6226 - val_loss: 1.8239 - val_accuracy: 0.3381 - val_mse: 27.6233
Epoch 5/10
1250/1250 [==============================] - 30s 24ms/step - loss: 1.7391 - accuracy: 0.3683 - mse: 27.6233 - val_loss: 1.8223 - val_accuracy: 0.3376 - val_mse: 27.6233
Epoch 6/10
1250/1250 [==============================] - 29s 23ms/step - loss: 1.7202 - accuracy: 0.3

In [ ]:
model.evaluate(test_X,test_y, verbose=2)


313/313 - 3s - loss: 0.8281 - accuracy: 0.7500 - mse: 27.6754 - 3s/epoch - 10ms/step


[0.8280676603317261, 0.75, 27.675443649291992]

In [ ]:
def getOneImage(dir, length, width):
  from PIL import Image
  from tensorflow.keras.preprocessing import image
  img = image.load_img(dir, target_size=(length,width))
  arrimg = image.img_to_array(img)
  arrimg = np.array([arrimg])
  return arrimg.astype('float32') / 255.0

In [ ]:
cat = getOneImage('gato.jpg',64,64)

In [ ]:
cat[0]

In [ ]:
np.argmax(model.predict(cat), axis=-1)


array([5])

In [ ]:
horse = getOneImage('caballo.jpg',64,64)

In [ ]:
np.argmax(model.predict(horse), axis=-1)

array([0])

In [ ]:
mar = getOneImage('mariposa.jpg',64,64)

In [ ]:
np.argmax(model.predict(mar), axis=-1)

array([4])